[package]
name = "mu-backend"
version = "0.1.0"
authors = ["ticki <ticki@noreply.github.com>"]
edition = "2018"

[dependencies]
rand = "0.6"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8"
chrono = { version = "0.4", features = ["serde"] }
